title: "Manish's Coding Journey"
email: "mrathaur704@gmail.com"
description: "My daily coding learning blog and portfolio documentation."
baseurl: "/blog"
url: "https://www.manishrathaur.tech"

author: "Manish Rathaur"

# ✏️ Fill in your social URLs below
github_username:  Rawdyrathaur
twitter_username: mrathaur704
linkedin_username: "manish-rathaur"
instagram_username: "mrathaur704"
youtube_username: "@manishcoding"

remote_theme: "zivong/jekyll-theme-hamilton"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
skin: midnight
