title: "Manish's Coding Journey"
email: "mrathaur704@gmail.com"
description: "My daily coding learning blog and portfolio documentation."
baseurl: "/blog"
url: "https://www.manishrathaur.tech"
twitter_username: mrathaur704
github_username:  Rawdyrathaur

# Social Integrations for Hamilton Left-Sidebar
author: "Manish Rathaur"
avatar: "https://manishrathaur.tech"

# Theme Activation Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Hamilton Dark Theme Source
remote_theme: "zivong/jekyll-theme-hamilton"
